Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.box_check_update = false

 
  config.vm.define "m1" do |m1|
    # Настройки для "m1"
    m1.vm.provider "virtualbox" do |vb|
      vb.name = "vm1"
      vb.memory = 1024
      vb.cpus = 1
    end

    m1.vm.hostname = "vm1"
    m1.vm.network "private_network", type: "bridge", bridge: "wlp2s0", ip: "192.168.56.4"

  end

end


