Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  
 # config.ssh.username = 'v'
  # пароль пользователя
 # config.ssh.password = 'v'
  # можно подключаться по паролю
 # config.ssh.keys_only = false

config.vm.provision "update", type: "shell", inline: "apt-get update"
config.vm.provision "netstat", type: "shell", inline: "echo Installing netstat; apt-get install -y net-tools"
config.vm.provision "nginx", type: "shell", inline: "echo Installing Nginx; apt-get install -y nginx"
  
  config.vm.network "forwarded_port", guest: 80, host: 8080
  
 config.vm.provider "virtualbox" do |vb|
    # имя виртуальной машины
    vb.name = "ubuntu2004"
    # объем оперативной памяти
    vb.memory = 2048
    # количество ядер процессора
    vb.cpus = 1
  end

end

